<a href="https://colab.research.google.com/github/dineshbasnet/SimpleNN/blob/main/pipelines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder

In [ ]:
df = pd.read_csv('/content/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

## Train test split

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## Scaling

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
X_train

array([[ 0.03529645,  0.2036685 ,  0.04551809, ...,  0.96721657,
         2.89233298,  0.95825783],
       [ 0.4182086 ,  1.08867244,  0.41094556, ..., -0.10482291,
        -0.1816253 , -1.19615618],
       [-0.8262559 , -0.27798244, -0.77024616, ...,  0.04278753,
         0.60742058,  2.55038268],
       ...,
       [ 1.71737484,  2.36516606,  1.85519744, ...,  2.17792042,
         1.83921764,  2.23083649],
       [-0.16162981,  0.77073537,  0.01020534, ...,  1.51889197,
         1.0628218 ,  3.30159651],
       [-0.70317699,  0.19417784, -0.68414653, ..., -0.5940248 ,
         0.38604498, -0.2431237 ]])

In [ ]:
y_train

199    M
13     M
242    B
67     B
227    B
      ..
472    B
257    M
567    M
14     M
160    B
Name: diagnosis, Length: 455, dtype: object

## Label Encoding

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_train

array([1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0])

## Numpy arrays to PyTorch tensors

In [ ]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
X_train_tensor

tensor([[ 0.0353,  0.2037,  0.0455,  ...,  0.9672,  2.8923,  0.9583],
        [ 0.4182,  1.0887,  0.4109,  ..., -0.1048, -0.1816, -1.1962],
        [-0.8263, -0.2780, -0.7702,  ...,  0.0428,  0.6074,  2.5504],
        ...,
        [ 1.7174,  2.3652,  1.8552,  ...,  2.1779,  1.8392,  2.2308],
        [-0.1616,  0.7707,  0.0102,  ...,  1.5189,  1.0628,  3.3016],
        [-0.7032,  0.1942, -0.6841,  ..., -0.5940,  0.3860, -0.2431]],
       dtype=torch.float64)

In [ ]:
X_train_tensor.shape

torch.Size([455, 30])

## Defining the model

In [ ]:
class SimpleNN():
  def __init__(self,X):

    self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

    # calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

## Important parameters

In [ ]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [ ]:
# create model
model = SimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model.forward(X_train_tensor)

  # loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)

  # backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epochs
  print(f'Epoch: {epoch+1}, Loss: {loss.item():.4f}')

Epoch: 1, Loss: 3.2509
Epoch: 2, Loss: 3.1020
Epoch: 3, Loss: 2.9435
Epoch: 4, Loss: 2.7858
Epoch: 5, Loss: 2.6186
Epoch: 6, Loss: 2.4447
Epoch: 7, Loss: 2.2702
Epoch: 8, Loss: 2.0974
Epoch: 9, Loss: 1.9220
Epoch: 10, Loss: 1.7510
Epoch: 11, Loss: 1.5854
Epoch: 12, Loss: 1.4296
Epoch: 13, Loss: 1.2892
Epoch: 14, Loss: 1.1666
Epoch: 15, Loss: 1.0636
Epoch: 16, Loss: 0.9807
Epoch: 17, Loss: 0.9166
Epoch: 18, Loss: 0.8690
Epoch: 19, Loss: 0.8344
Epoch: 20, Loss: 0.8096
Epoch: 21, Loss: 0.7917
Epoch: 22, Loss: 0.7784
Epoch: 23, Loss: 0.7684
Epoch: 24, Loss: 0.7605
Epoch: 25, Loss: 0.7543

In [ ]:
model.weights

tensor([[ 0.5604],
        [-0.2168],
        [ 0.1388],
        [-0.1206],
        [-0.3285],
        [-0.4402],
        [-0.2528],
        [ 0.0235],
        [ 0.3727],
        [ 0.5929],
        [-0.0483],
        [ 0.5910],
        [-0.1861],
        [-0.0683],
        [ 0.0868],
        [-0.1175],
        [ 0.2780],
        [ 0.0372],
        [-0.1234],
        [-0.1527],
        [-0.2363],
        [-0.0552],
        [-0.1286],
        [ 0.5624],
        [ 0.0259],
        [-0.4289],
        [ 0.1173],
        [ 0.0614],
        [ 0.3022],
        [ 0.3664]], dtype=torch.float64, requires_grad=True)

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item():.4f}')

Accuracy: 0.7285